services:
  params-ftp:
    image: zkwasm/params
    network_mode: "host"
    attach: false
    # ports:
    #   - "21:21"
    #   - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: ftppassword
      FTP_USER_HOME: /home/ftpuser
      # ADDED_FLAGS: "-p 2121:2121 -p 30000-31000:30000-31000"
    healthcheck:
      # Basic health check to ensure the FTP server is running
      test: "ls -l /var/run/pure-ftpd.pid"
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 3
  rocksdb:
    image: rhaoio/rhaoio-rocksdb
    attach: false
    volumes:
      - rocksdb_data:/home/zkwasm/prover-node-release/rocksdb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-f", "/rocksdb/.initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    container_name: zkwasm-rocksdb-data
  prover-dry-run-service:
    image: zkwasm:latest
    attach: false
    runtime: nvidia
    network_mode: "host"
    user: "1001:1001"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: pgrep -f zkwasm-playground
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./prover_config.json:/home/zkwasm/prover-node-release/prover_config.json
      - ./dry_run_config.json:/home/zkwasm/prover-node-release/dry_run_config.json
      # Volume for the whole workspace directory to persist workspace data
      # may have to consider handling changes in the workspace directory (delete volume probably)
      - workspace-volume:/home/zkwasm/prover-node-release/workspace
      # Volume for the rocksdb data directory to persist rocksdb data
      - rocksdb_data:/home/zkwasm/prover-node-release/rocksdb
      # Volume for the logs directory to persist logs
      - dry-run-logs-volume:/home/zkwasm/prover-node-release/logs/dry_run
      # configure huge pages for the prover
      - /dev/hugepages:/dev/hugepages
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=Etc/UTC
    # Override default command to run as a dry-run service
    command: bash -c "
      time=$$(date +%Y-%m-%d-%H-%M-%S)

      RUST_LOG=info ./target/release/zkwasm-playground --dryrunconfig dry_run_config.json -w workspace --dryrun=prover --rocksdbworkspace rocksdb \
      2>&1 | sudo rotatelogs -e -n 10 logs/dry_run/dry_run_$${time}.log 100M"
  prover-node:
    image: zkwasm:latest
    runtime: nvidia
    network_mode: "host"
    depends_on:
      prover-dry-run-service:
        condition: service_healthy
      params-ftp:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Use all GPUs available on the system by default
              # count: all
              # If you want to specify which GPUs to use, uncomment the following line
              # and specify the GPU IDs. You can run `nvidia-smi` to see the GPU IDs.
              # Ensure 'count' field above is commented out if uncommenting the following line as they are mutually exclusive.
              # ref:: https://docs.docker.com/compose/gpu-support/
              # By default we just use the first GPU
              device_ids: ["0"]
              capabilities: [gpu]
    user: "1001:1001"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prover_config.json:/home/zkwasm/prover-node-release/prover_config.json
      - ./dry_run_config.json:/home/zkwasm/prover-node-release/dry_run_config.json
      # Volume for the whole workspace directory to persist workspace data
      # may have to consider handling changes in the workspace directory (delete volume probably)
      - workspace-volume:/home/zkwasm/prover-node-release/workspace
      # Volume for the rocksdb data directory to persist rocksdb data
      - rocksdb_data:/home/zkwasm/prover-node-release/rocksdb
      # Volume for the logs directory to persist logs
      - prover-logs-volume:/home/zkwasm/prover-node-release/logs/prover
      # configure huge pages for the prover
      - /dev/hugepages:/dev/hugepages
      # Starting script for the prover
      - ./_start_prover-node-service.sh:/home/zkwasm/prover-node-release/_start_prover-node-service.sh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=Etc/UTC
    command:
      [
        "/bin/bash",
        "/home/zkwasm/prover-node-release/_start_prover-node-service.sh",
      ]
volumes:
  workspace-volume:
  prover-logs-volume:
  dry-run-logs-volume:
  rocksdb_data:
