services:
  mongodb:
    image: mongo:latest
    network_mode: "host"
    # ports:
    #   - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongod.conf:/data/configdb/mongod.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: --config /data/configdb/mongod.conf --port ${MONGODB_PORT}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGODB_PORT}/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: zkwasm-mongodb
    restart: always
    environment:
      MONGODB_PORT: 27017
  prover-dry-run-service:
    image: zkwasm:latest
    runtime: nvidia
    network_mode: "host"
    user: "1001:1001"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./prover_config.json:/home/zkwasm/prover-node-release/prover_config.json
      - ./dry_run_config.json:/home/zkwasm/prover-node-release/dry_run_config.json
      # Volume for the whole workspace directory to persist workspace data
      # may have to consider handling changes in the workspace directory (delete volume probably)
      - workspace-volume:/home/zkwasm/prover-node-release/workspace
      # Volume for the logs directory to persist logs
      - dry-run-logs-volume:/home/zkwasm/prover-node-release/logs/dry_run
      # configure huge pages for the prover
      - /dev/hugepages:/dev/hugepages
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=Etc/UTC
    # Override default command to run as a dry-run service
    command: bash -c "
      time=$$(date +%Y-%m-%d-%H-%M-%S)

      RUST_LOG=info ./target/release/zkwasm-playground --dryrunconfig dry_run_config.json -w workspace --dryrun=prover \
      2>&1 | sudo rotatelogs -e -n 10 logs/dry_run/dry_run_$${time}.log 100M"
  prover-node:
    image: zkwasm:latest
    runtime: nvidia
    network_mode: "host"
    depends_on:
      mongodb:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Use all GPUs available on the system by default
              count: all
              # If you want to specify which GPUs to use, uncomment the following line
              # and specify the GPU IDs. You can run `nvidia-smi` to see the GPU IDs.
              # Ensure 'count' field above is commented out if uncommenting the following line as they are mutually exclusive.
              # ref:: https://docs.docker.com/compose/gpu-support/
              # device_ids: ['0', '1']
              capabilities: [gpu]
    user: "1001:1001"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prover_config.json:/home/zkwasm/prover-node-release/prover_config.json
      - ./dry_run_config.json:/home/zkwasm/prover-node-release/dry_run_config.json
      # Volume for the whole workspace directory to persist workspace data
      # may have to consider handling changes in the workspace directory (delete volume probably)
      - workspace-volume:/home/zkwasm/prover-node-release/workspace
      # Volume for the logs directory to persist logs
      - prover-logs-volume:/home/zkwasm/prover-node-release/logs/prover
      # configure huge pages for the prover
      - /dev/hugepages:/dev/hugepages
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=Etc/UTC
    command: bash -c "
      nvidia-smi && \
      wget -r -nH --cut-dirs=1 --no-parent --user=ftpuser --password=ftppassword ftp://localhost/params/ -P /home/zkwasm/prover-node-release/workspace/static/ &&
      time=$$(date +%Y-%m-%d-%H-%M-%S)
      CUDA_VISIBLE_DEVICES=0 RUST_LOG=info RUST_BACKTRACE=1 ./target/release/zkwasm-playground --config prover_config.json -w workspace --dryrunconfig dry_run_config.json -p \
      2>&1 | rotatelogs -e -n 10 logs/prover/prover_$${time}.log 100M"
volumes:
  workspace-volume:
  prover-logs-volume:
  dry-run-logs-volume:
