version: "3.9"

services:
  prover-node:
    image: rhaoio/prover-node-dev:0.0.14
    runtime: nvidia
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Use all GPUs available on the system by default
              # count: all
              # If you want to specify which GPUs to use, uncomment the following line
              # and specify the GPU IDs. You can run `nvidia-smi` to see the GPU IDs.
              # Ensure 'count' field above is commented out if uncommenting the following line as they are mutually exclusive.
              # ref:: https://docs.docker.com/compose/gpu-support/
              # By default we just use the first GPU
              device_ids: ["0"]
              capabilities: [gpu]
    user: "1001:1001"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prover_config.json:/home/zkwasm/prover-node-release/prover_config.json
      - ./dry_run_config.json:/home/zkwasm/prover-node-release/dry_run_config.json
      - ./prover_system_config.json:/home/zkwasm/prover-node-release/prover_system_config.json
      # Volume for the whole workspace directory to persist workspace data
      # may have to consider handling changes in the workspace directory (delete volume probably)
      - workspace-volume:/home/zkwasm/prover-node-release/workspace
      # Volume for the rocksdb data directory to persist rocksdb data
      - rocksdb_data:/home/zkwasm/prover-node-release/rocksdb
      # Volume for the logs directory to persist logs
      - prover-logs-volume:/home/zkwasm/prover-node-release/logs/prover
      # configure huge pages for the prover
      - /dev/hugepages:/dev/hugepages
      # Starting script for the prover
      - ./_start_prover-node-service.sh:/home/zkwasm/prover-node-release/_start_prover-node-service.sh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=Etc/UTC
    command:
      [
        "/bin/bash",
        "/home/zkwasm/prover-node-release/_start_prover-node-service.sh",
      ]
  monitor:
    image: docker:27.5.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/.env:/.env
      - ./scripts/monitor.sh:/monitor.sh
    command: /bin/sh -c "apk add bash curl && bash monitor.sh"
    depends_on:
      - prover-node
    profiles:
      - ${RUN_MONITOR}
volumes:
  workspace-volume:
  prover-logs-volume:
  dry-run-logs-volume:
  rocksdb_data:
